routes/web.php
<?php

Route::redirect('/', '/login');
Route::get('/home', function () {
    if (session('status')) {
        return redirect()->route('admin.home')->with('status', session('status'));
    }

    return redirect()->route('admin.home');
});

Auth::routes(['register' => false]);

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    // Permissions
    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'PermissionsController');

    // Roles
    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'RolesController');

    // Users
    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    Route::resource('users', 'UsersController');

    // Audit Logs
    Route::resource('audit-logs', 'AuditLogsController', ['except' => ['create', 'store', 'edit', 'update', 'destroy']]);

    // Cursos
    Route::delete('cursos/destroy', 'CursosController@massDestroy')->name('cursos.massDestroy');
    Route::resource('cursos', 'CursosController');

    // Materia
    Route::delete('materia/destroy', 'MateriaController@massDestroy')->name('materia.massDestroy');
    Route::resource('materia', 'MateriaController');

    // Tareas
    Route::delete('tareas/destroy', 'TareasController@massDestroy')->name('tareas.massDestroy');
    Route::post('tareas/media', 'TareasController@storeMedia')->name('tareas.storeMedia');
    Route::get('tareas/addtarea/{id}', 'TareasController@addTarea')->name('tareas.addTarea');
    Route::get('tareas/editorTarea/{idtarea}', 'TareasController@editorTarea')->name('tareas.editor');
    Route::get('tareas/storetareadetalle', 'TareasController@storeTareaDetalle')->name('tareas.storetareadetalle');
    Route::get('tareas/realizartareaestudiante/{idtarea}', 'TareasController@realizarTareaEstudiante')->name('tareas.realizarTareaEstudiante');
    Route::post('tareas/ckmedia', 'TareasController@storeCKEditorImages')->name('tareas.storeCKEditorImages');
    Route::resource('tareas', 'TareasController');

    // Tarea Estudiante
    Route::delete('tarea-estudiantes/destroy', 'TareaEstudianteController@massDestroy')->name('tarea-estudiantes.massDestroy');
    Route::resource('tarea-estudiantes', 'TareaEstudianteController');

    // Estudiante
    Route::delete('estudiantes/destroy', 'EstudianteController@massDestroy')->name('estudiantes.massDestroy');
    Route::resource('estudiantes', 'EstudianteController');

    // Representante
    Route::delete('representantes/destroy', 'RepresentanteController@massDestroy')->name('representantes.massDestroy');
    Route::resource('representantes', 'RepresentanteController');

    // Respuestas
    Route::resource('respuesta', 'RespuestasController', ['except' => ['create', 'store', 'edit', 'update', 'show', 'destroy']]);

    // Parametro Respuesta
    Route::delete('parametro-respuesta/destroy', 'ParametroRespuestaController@massDestroy')->name('parametro-respuesta.massDestroy');
    Route::resource('parametro-respuesta', 'ParametroRespuestaController');

    // Libro
    Route::delete('libros/destroy', 'LibroController@massDestroy')->name('libros.massDestroy');
    Route::resource('libros', 'LibroController');

    // Codigo Libro
    Route::resource('codigo-libros', 'CodigoLibroController', ['except' => ['edit', 'update', 'show', 'destroy']]);

    // Codigo Estudiante
    Route::delete('codigo-estudiantes/destroy', 'CodigoEstudianteController@massDestroy')->name('codigo-estudiantes.massDestroy');
    Route::resource('codigo-estudiantes', 'CodigoEstudianteController');
});
Route::group(['prefix' => 'profile', 'as' => 'profile.', 'namespace' => 'Auth', 'middleware' => ['auth']], function () {
    // Change password
    if (file_exists(app_path('Http/Controllers/Auth/ChangePasswordController.php'))) {
        Route::get('password', 'ChangePasswordController@edit')->name('password.edit');
        Route::post('password', 'ChangePasswordController@update')->name('password.update');
        Route::post('profile', 'ChangePasswordController@updateProfile')->name('password.updateProfile');
        Route::post('profile/destroy', 'ChangePasswordController@destroy')->name('password.destroyProfile');
    }
});

app/Http/Controllers/Admin/ParametroRespuestaController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\MassDestroyParametroRespuestumRequest;
use App\Http\Requests\StoreParametroRespuestumRequest;
use App\Http\Requests\UpdateParametroRespuestumRequest;
use App\Models\ParametroRespuestum;
use Gate;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;

class ParametroRespuestaController extends Controller
{
    public function index()
    {
        abort_if(Gate::denies('parametro_respuestum_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $parametroRespuesta = ParametroRespuestum::with(['respuesta'])->get();

        return view('admin.parametroRespuesta.index', compact('parametroRespuesta'));
    }

    public function create()
    {
        abort_if(Gate::denies('parametro_respuestum_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.parametroRespuesta.create');
    }

    public function store(StoreParametroRespuestumRequest $request)
    {
        $parametroRespuestum = ParametroRespuestum::create($request->all());

        return redirect()->route('admin.parametro-respuesta.index');
    }

    public function edit(ParametroRespuestum $parametroRespuestum)
    {
        abort_if(Gate::denies('parametro_respuestum_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $parametroRespuestum->load('respuesta');

        return view('admin.parametroRespuesta.edit', compact('parametroRespuestum'));
    }

    public function update(UpdateParametroRespuestumRequest $request, ParametroRespuestum $parametroRespuestum)
    {
        $parametroRespuestum->update($request->all());

        return redirect()->route('admin.parametro-respuesta.index');
    }

    public function show(ParametroRespuestum $parametroRespuestum)
    {
        abort_if(Gate::denies('parametro_respuestum_show'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $parametroRespuestum->load('respuesta');

        return view('admin.parametroRespuesta.show', compact('parametroRespuestum'));
    }

    public function destroy(ParametroRespuestum $parametroRespuestum)
    {
        abort_if(Gate::denies('parametro_respuestum_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $parametroRespuestum->delete();

        return back();
    }

    public function massDestroy(MassDestroyParametroRespuestumRequest $request)
    {
        ParametroRespuestum::whereIn('id', request('ids'))->delete();

        return response(null, Response::HTTP_NO_CONTENT);
    }
}

resources/views/admin/parametroRespuesta/create.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.create') }} {{ trans('cruds.parametroRespuestum.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.parametro-respuesta.store") }}" enctype="multipart/form-data">
            @csrf
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
    </div>
</div>



@endsection

resources/views/admin/parametroRespuesta/edit.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.edit') }} {{ trans('cruds.parametroRespuestum.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.parametro-respuesta.update", [$parametroRespuestum->id]) }}" enctype="multipart/form-data">
            @method('PUT')
            @csrf
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
    </div>
</div>



@endsection

resources/views/admin/parametroRespuesta/index.blade.php
@extends('layouts.admin')
@section('content')
@can('parametro_respuestum_create')
    <div style="margin-bottom: 10px;" class="row">
        <div class="col-lg-12">
            <a class="btn btn-success" href="{{ route('admin.parametro-respuesta.create') }}">
                {{ trans('global.add') }} {{ trans('cruds.parametroRespuestum.title_singular') }}
            </a>
        </div>
    </div>
@endcan
<div class="card">
    <div class="card-header">
        {{ trans('cruds.parametroRespuestum.title_singular') }} {{ trans('global.list') }}
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <table class=" table table-bordered table-striped table-hover datatable datatable-ParametroRespuestum">
                <thead>
                    <tr>
                        <th width="10">

                        </th>
                        <th>
                            {{ trans('cruds.parametroRespuestum.fields.id') }}
                        </th>
                        <th>
                            &nbsp;
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($parametroRespuesta as $key => $parametroRespuestum)
                        <tr data-entry-id="{{ $parametroRespuestum->id }}">
                            <td>

                            </td>
                            <td>
                                {{ $parametroRespuestum->id ?? '' }}
                            </td>
                            <td>
                                @can('parametro_respuestum_show')
                                    <a class="btn btn-xs btn-primary" href="{{ route('admin.parametro-respuesta.show', $parametroRespuestum->id) }}">
                                        {{ trans('global.view') }}
                                    </a>
                                @endcan

                                @can('parametro_respuestum_edit')
                                    <a class="btn btn-xs btn-info" href="{{ route('admin.parametro-respuesta.edit', $parametroRespuestum->id) }}">
                                        {{ trans('global.edit') }}
                                    </a>
                                @endcan

                                @can('parametro_respuestum_delete')
                                    <form action="{{ route('admin.parametro-respuesta.destroy', $parametroRespuestum->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                                    </form>
                                @endcan

                            </td>

                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>



@endsection
@section('scripts')
@parent
<script>
    $(function () {
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
@can('parametro_respuestum_delete')
  let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
  let deleteButton = {
    text: deleteButtonTrans,
    url: "{{ route('admin.parametro-respuesta.massDestroy') }}",
    className: 'btn-danger',
    action: function (e, dt, node, config) {
      var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {
          return $(entry).data('entry-id')
      });

      if (ids.length === 0) {
        alert('{{ trans('global.datatables.zero_selected') }}')

        return
      }

      if (confirm('{{ trans('global.areYouSure') }}')) {
        $.ajax({
          headers: {'x-csrf-token': _token},
          method: 'POST',
          url: config.url,
          data: { ids: ids, _method: 'DELETE' }})
          .done(function () { location.reload() })
      }
    }
  }
  dtButtons.push(deleteButton)
@endcan

  $.extend(true, $.fn.dataTable.defaults, {
    orderCellsTop: true,
    order: [[ 1, 'desc' ]],
    pageLength: 100,
  });
  let table = $('.datatable-ParametroRespuestum:not(.ajaxTable)').DataTable({ buttons: dtButtons })
  $('a[data-toggle="tab"]').on('shown.bs.tab click', function(e){
      $($.fn.dataTable.tables(true)).DataTable()
          .columns.adjust();
  });
  
})

</script>
@endsection

resources/views/admin/parametroRespuesta/show.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.show') }} {{ trans('cruds.parametroRespuestum.title') }}
    </div>

    <div class="card-body">
        <div class="form-group">
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('admin.parametro-respuesta.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
            <table class="table table-bordered table-striped">
                <tbody>
                    <tr>
                        <th>
                            {{ trans('cruds.parametroRespuestum.fields.id') }}
                        </th>
                        <td>
                            {{ $parametroRespuestum->id }}
                        </td>
                    </tr>
                </tbody>
            </table>
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('admin.parametro-respuesta.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
        </div>
    </div>
</div>



@endsection