routes/web.php
<?php

Route::redirect('/', '/login');
Route::get('/home', function () {
    if (session('status')) {
        return redirect()->route('admin.home')->with('status', session('status'));
    }

    return redirect()->route('admin.home');
});

Auth::routes(['register' => false]);

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    // Permissions
    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'PermissionsController');

    // Roles
    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'RolesController');

    // Users
    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    Route::resource('users', 'UsersController');

    // Audit Logs
    Route::resource('audit-logs', 'AuditLogsController', ['except' => ['create', 'store', 'edit', 'update', 'destroy']]);

    // Cursos
    Route::delete('cursos/destroy', 'CursosController@massDestroy')->name('cursos.massDestroy');
    Route::resource('cursos', 'CursosController');

    // Materia
    Route::delete('materia/destroy', 'MateriaController@massDestroy')->name('materia.massDestroy');
    Route::resource('materia', 'MateriaController');

    // Tareas
    Route::delete('tareas/destroy', 'TareasController@massDestroy')->name('tareas.massDestroy');
    Route::post('tareas/media', 'TareasController@storeMedia')->name('tareas.storeMedia');
    Route::get('tareas/addtarea/{id}', 'TareasController@addTarea')->name('tareas.addTarea');
    Route::get('tareas/editorTarea/{idtarea}', 'TareasController@editorTarea')->name('tareas.editor');
    Route::get('tareas/storetareadetalle', 'TareasController@storeTareaDetalle')->name('tareas.storetareadetalle');
    Route::get('tareas/realizartareaestudiante/{idtarea}', 'TareasController@realizarTareaEstudiante')->name('tareas.realizarTareaEstudiante');
    Route::post('tareas/ckmedia', 'TareasController@storeCKEditorImages')->name('tareas.storeCKEditorImages');
    Route::resource('tareas', 'TareasController');

    // Tarea Estudiante
    Route::delete('tarea-estudiantes/destroy', 'TareaEstudianteController@massDestroy')->name('tarea-estudiantes.massDestroy');
    Route::resource('tarea-estudiantes', 'TareaEstudianteController');

    // Estudiante
    Route::delete('estudiantes/destroy', 'EstudianteController@massDestroy')->name('estudiantes.massDestroy');
    Route::resource('estudiantes', 'EstudianteController');

    // Representante
    Route::delete('representantes/destroy', 'RepresentanteController@massDestroy')->name('representantes.massDestroy');
    Route::resource('representantes', 'RepresentanteController');

    // Respuestas
    Route::resource('respuesta', 'RespuestasController', ['except' => ['create', 'store', 'edit', 'update', 'show', 'destroy']]);

    // Parametro Respuesta
    Route::delete('parametro-respuesta/destroy', 'ParametroRespuestaController@massDestroy')->name('parametro-respuesta.massDestroy');
    Route::resource('parametro-respuesta', 'ParametroRespuestaController');

    // Libro
    Route::delete('libros/destroy', 'LibroController@massDestroy')->name('libros.massDestroy');
    Route::resource('libros', 'LibroController');

    // Codigo Libro
    Route::resource('codigo-libros', 'CodigoLibroController', ['except' => ['edit', 'update', 'show', 'destroy']]);

    // Codigo Estudiante
    Route::delete('codigo-estudiantes/destroy', 'CodigoEstudianteController@massDestroy')->name('codigo-estudiantes.massDestroy');
    Route::resource('codigo-estudiantes', 'CodigoEstudianteController');
});
Route::group(['prefix' => 'profile', 'as' => 'profile.', 'namespace' => 'Auth', 'middleware' => ['auth']], function () {
    // Change password
    if (file_exists(app_path('Http/Controllers/Auth/ChangePasswordController.php'))) {
        Route::get('password', 'ChangePasswordController@edit')->name('password.edit');
        Route::post('password', 'ChangePasswordController@update')->name('password.update');
        Route::post('profile', 'ChangePasswordController@updateProfile')->name('password.updateProfile');
        Route::post('profile/destroy', 'ChangePasswordController@destroy')->name('password.destroyProfile');
    }
});

app/Models/CodigoEstudiante.php
<?php

namespace App\Models;

use \DateTimeInterface;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class CodigoEstudiante extends Model
{
    use SoftDeletes;
    use HasFactory;

    public $table = 'codigo_estudiantes';

    protected $dates = [
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected $fillable = [
        'libro_id',
        'estudiante_id',
        'codigo',
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    public function libro()
    {
        return $this->belongsTo(Libro::class, 'libro_id');
    }

    public function estudiante()
    {
        return $this->belongsTo(User::class, 'estudiante_id');
    }

    protected function serializeDate(DateTimeInterface $date)
    {
        return $date->format('Y-m-d H:i:s');
    }
}

app/Http/Controllers/Admin/CodigoEstudianteController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\MassDestroyCodigoEstudianteRequest;
use App\Http\Requests\StoreCodigoEstudianteRequest;
use App\Http\Requests\UpdateCodigoEstudianteRequest;
use App\Models\CodigoEstudiante;
use App\Models\Libro;
use App\Models\User;
use Gate;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;

class CodigoEstudianteController extends Controller
{
    public function index()
    {
        abort_if(Gate::denies('codigo_estudiante_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $codigoEstudiantes = CodigoEstudiante::with(['libro', 'estudiante'])->get();

        return view('admin.codigoEstudiantes.index', compact('codigoEstudiantes'));
    }

    public function create()
    {
        abort_if(Gate::denies('codigo_estudiante_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $libros = Libro::pluck('nombre', 'id')->prepend(trans('global.pleaseSelect'), '');

        $estudiantes = User::pluck('name', 'id')->prepend(trans('global.pleaseSelect'), '');

        return view('admin.codigoEstudiantes.create', compact('libros', 'estudiantes'));
    }

    public function store(StoreCodigoEstudianteRequest $request)
    {
        $codigoEstudiante = CodigoEstudiante::create($request->all());

        return redirect()->route('admin.codigo-estudiantes.index');
    }

    public function edit(CodigoEstudiante $codigoEstudiante)
    {
        abort_if(Gate::denies('codigo_estudiante_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $libros = Libro::pluck('nombre', 'id')->prepend(trans('global.pleaseSelect'), '');

        $estudiantes = User::pluck('name', 'id')->prepend(trans('global.pleaseSelect'), '');

        $codigoEstudiante->load('libro', 'estudiante');

        return view('admin.codigoEstudiantes.edit', compact('libros', 'estudiantes', 'codigoEstudiante'));
    }

    public function update(UpdateCodigoEstudianteRequest $request, CodigoEstudiante $codigoEstudiante)
    {
        $codigoEstudiante->update($request->all());

        return redirect()->route('admin.codigo-estudiantes.index');
    }

    public function show(CodigoEstudiante $codigoEstudiante)
    {
        abort_if(Gate::denies('codigo_estudiante_show'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $codigoEstudiante->load('libro', 'estudiante');

        return view('admin.codigoEstudiantes.show', compact('codigoEstudiante'));
    }

    public function destroy(CodigoEstudiante $codigoEstudiante)
    {
        abort_if(Gate::denies('codigo_estudiante_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $codigoEstudiante->delete();

        return back();
    }

    public function massDestroy(MassDestroyCodigoEstudianteRequest $request)
    {
        CodigoEstudiante::whereIn('id', request('ids'))->delete();

        return response(null, Response::HTTP_NO_CONTENT);
    }
}

resources/views/admin/codigoEstudiantes/create.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.create') }} {{ trans('cruds.codigoEstudiante.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.codigo-estudiantes.store") }}" enctype="multipart/form-data">
            @csrf
            <div class="form-group">
                <label for="libro_id">{{ trans('cruds.codigoEstudiante.fields.libro') }}</label>
                <select class="form-control select2 {{ $errors->has('libro') ? 'is-invalid' : '' }}" name="libro_id" id="libro_id">
                    @foreach($libros as $id => $entry)
                        <option value="{{ $id }}" {{ old('libro_id') == $id ? 'selected' : '' }}>{{ $entry }}</option>
                    @endforeach
                </select>
                @if($errors->has('libro'))
                    <span class="text-danger">{{ $errors->first('libro') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.codigoEstudiante.fields.libro_helper') }}</span>
            </div>
            <div class="form-group">
                <label for="estudiante_id">{{ trans('cruds.codigoEstudiante.fields.estudiante') }}</label>
                <select class="form-control select2 {{ $errors->has('estudiante') ? 'is-invalid' : '' }}" name="estudiante_id" id="estudiante_id">
                    @foreach($estudiantes as $id => $entry)
                        <option value="{{ $id }}" {{ old('estudiante_id') == $id ? 'selected' : '' }}>{{ $entry }}</option>
                    @endforeach
                </select>
                @if($errors->has('estudiante'))
                    <span class="text-danger">{{ $errors->first('estudiante') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.codigoEstudiante.fields.estudiante_helper') }}</span>
            </div>
            <div class="form-group">
                <label for="codigo">{{ trans('cruds.codigoEstudiante.fields.codigo') }}</label>
                <input class="form-control {{ $errors->has('codigo') ? 'is-invalid' : '' }}" type="text" name="codigo" id="codigo" value="{{ old('codigo', '') }}">
                @if($errors->has('codigo'))
                    <span class="text-danger">{{ $errors->first('codigo') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.codigoEstudiante.fields.codigo_helper') }}</span>
            </div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
    </div>
</div>



@endsection

resources/views/admin/codigoEstudiantes/edit.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.edit') }} {{ trans('cruds.codigoEstudiante.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.codigo-estudiantes.update", [$codigoEstudiante->id]) }}" enctype="multipart/form-data">
            @method('PUT')
            @csrf
            <div class="form-group">
                <label for="libro_id">{{ trans('cruds.codigoEstudiante.fields.libro') }}</label>
                <select class="form-control select2 {{ $errors->has('libro') ? 'is-invalid' : '' }}" name="libro_id" id="libro_id">
                    @foreach($libros as $id => $entry)
                        <option value="{{ $id }}" {{ (old('libro_id') ? old('libro_id') : $codigoEstudiante->libro->id ?? '') == $id ? 'selected' : '' }}>{{ $entry }}</option>
                    @endforeach
                </select>
                @if($errors->has('libro'))
                    <span class="text-danger">{{ $errors->first('libro') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.codigoEstudiante.fields.libro_helper') }}</span>
            </div>
            <div class="form-group">
                <label for="estudiante_id">{{ trans('cruds.codigoEstudiante.fields.estudiante') }}</label>
                <select class="form-control select2 {{ $errors->has('estudiante') ? 'is-invalid' : '' }}" name="estudiante_id" id="estudiante_id">
                    @foreach($estudiantes as $id => $entry)
                        <option value="{{ $id }}" {{ (old('estudiante_id') ? old('estudiante_id') : $codigoEstudiante->estudiante->id ?? '') == $id ? 'selected' : '' }}>{{ $entry }}</option>
                    @endforeach
                </select>
                @if($errors->has('estudiante'))
                    <span class="text-danger">{{ $errors->first('estudiante') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.codigoEstudiante.fields.estudiante_helper') }}</span>
            </div>
            <div class="form-group">
                <label for="codigo">{{ trans('cruds.codigoEstudiante.fields.codigo') }}</label>
                <input class="form-control {{ $errors->has('codigo') ? 'is-invalid' : '' }}" type="text" name="codigo" id="codigo" value="{{ old('codigo', $codigoEstudiante->codigo) }}">
                @if($errors->has('codigo'))
                    <span class="text-danger">{{ $errors->first('codigo') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.codigoEstudiante.fields.codigo_helper') }}</span>
            </div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
    </div>
</div>



@endsection

resources/views/admin/codigoEstudiantes/index.blade.php
@extends('layouts.admin')
@section('content')
@can('codigo_estudiante_create')
    <div style="margin-bottom: 10px;" class="row">
        <div class="col-lg-12">
            <a class="btn btn-success" href="{{ route('admin.codigo-estudiantes.create') }}">
                {{ trans('global.add') }} {{ trans('cruds.codigoEstudiante.title_singular') }}
            </a>
        </div>
    </div>
@endcan
<div class="card">
    <div class="card-header">
        {{ trans('cruds.codigoEstudiante.title_singular') }} {{ trans('global.list') }}
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <table class=" table table-bordered table-striped table-hover datatable datatable-CodigoEstudiante">
                <thead>
                    <tr>
                        <th width="10">

                        </th>
                        <th>
                            {{ trans('cruds.codigoEstudiante.fields.id') }}
                        </th>
                        <th>
                            {{ trans('cruds.codigoEstudiante.fields.libro') }}
                        </th>
                        <th>
                            {{ trans('cruds.codigoEstudiante.fields.estudiante') }}
                        </th>
                        <th>
                            {{ trans('cruds.codigoEstudiante.fields.codigo') }}
                        </th>
                        <th>
                            &nbsp;
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($codigoEstudiantes as $key => $codigoEstudiante)
                        <tr data-entry-id="{{ $codigoEstudiante->id }}">
                            <td>

                            </td>
                            <td>
                                {{ $codigoEstudiante->id ?? '' }}
                            </td>
                            <td>
                                {{ $codigoEstudiante->libro->nombre ?? '' }}
                            </td>
                            <td>
                                {{ $codigoEstudiante->estudiante->name ?? '' }}
                            </td>
                            <td>
                                {{ $codigoEstudiante->codigo ?? '' }}
                            </td>
                            <td>
                                @can('codigo_estudiante_show')
                                    <a class="btn btn-xs btn-primary" href="{{ route('admin.codigo-estudiantes.show', $codigoEstudiante->id) }}">
                                        {{ trans('global.view') }}
                                    </a>
                                @endcan

                                @can('codigo_estudiante_edit')
                                    <a class="btn btn-xs btn-info" href="{{ route('admin.codigo-estudiantes.edit', $codigoEstudiante->id) }}">
                                        {{ trans('global.edit') }}
                                    </a>
                                @endcan

                                @can('codigo_estudiante_delete')
                                    <form action="{{ route('admin.codigo-estudiantes.destroy', $codigoEstudiante->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                                    </form>
                                @endcan

                            </td>

                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>



@endsection
@section('scripts')
@parent
<script>
    $(function () {
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
@can('codigo_estudiante_delete')
  let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
  let deleteButton = {
    text: deleteButtonTrans,
    url: "{{ route('admin.codigo-estudiantes.massDestroy') }}",
    className: 'btn-danger',
    action: function (e, dt, node, config) {
      var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {
          return $(entry).data('entry-id')
      });

      if (ids.length === 0) {
        alert('{{ trans('global.datatables.zero_selected') }}')

        return
      }

      if (confirm('{{ trans('global.areYouSure') }}')) {
        $.ajax({
          headers: {'x-csrf-token': _token},
          method: 'POST',
          url: config.url,
          data: { ids: ids, _method: 'DELETE' }})
          .done(function () { location.reload() })
      }
    }
  }
  dtButtons.push(deleteButton)
@endcan

  $.extend(true, $.fn.dataTable.defaults, {
    orderCellsTop: true,
    order: [[ 1, 'desc' ]],
    pageLength: 100,
  });
  let table = $('.datatable-CodigoEstudiante:not(.ajaxTable)').DataTable({ buttons: dtButtons })
  $('a[data-toggle="tab"]').on('shown.bs.tab click', function(e){
      $($.fn.dataTable.tables(true)).DataTable()
          .columns.adjust();
  });
  
})

</script>
@endsection

resources/views/admin/codigoEstudiantes/show.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.show') }} {{ trans('cruds.codigoEstudiante.title') }}
    </div>

    <div class="card-body">
        <div class="form-group">
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('admin.codigo-estudiantes.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
            <table class="table table-bordered table-striped">
                <tbody>
                    <tr>
                        <th>
                            {{ trans('cruds.codigoEstudiante.fields.id') }}
                        </th>
                        <td>
                            {{ $codigoEstudiante->id }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.codigoEstudiante.fields.libro') }}
                        </th>
                        <td>
                            {{ $codigoEstudiante->libro->nombre ?? '' }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.codigoEstudiante.fields.estudiante') }}
                        </th>
                        <td>
                            {{ $codigoEstudiante->estudiante->name ?? '' }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.codigoEstudiante.fields.codigo') }}
                        </th>
                        <td>
                            {{ $codigoEstudiante->codigo }}
                        </td>
                    </tr>
                </tbody>
            </table>
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('admin.codigo-estudiantes.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
        </div>
    </div>
</div>



@endsection